const{Schema,model}=require("mongoose");

//mongoimport -h localhost -d DatabasLab01 -c datas --type csv --file owid-covid-data.csv --headerline

const dataSchema=new Schema({
    _id:{type:Schema.Types.ObjectId},
    aged_65_older:{type:Schema.Types.Mixed},
    aged_70_older:{type:Schema.Types.Mixed},
    cardiovasc_death_rate:{type:Schema.Types.Mixed},
    continent:{type:String},
    date:{type:String},
    diabetes_prevalence:{type:Schema.Types.Mixed},
    excess_mortality:{type:Schema.Types.Mixed},
    excess_mortality_cumulative:{type:Schema.Types.Mixed},
    excess_mortality_cumulative_absolute:{type:Schema.Types.Mixed},
    excess_mortality_cumulative_per_million:{type:Schema.Types.Mixed},
    extreme_poverty:{type:Schema.Types.Mixed},
    female_smokers:{type:Schema.Types.Mixed},
    gdp_per_capita:{type:Schema.Types.Mixed},
    handwashing_facilities:{type:Schema.Types.Mixed},
    hosp_patients:{type:Schema.Types.Mixed},
    hosp_patients_per_million:{type:Schema.Types.Mixed},
    hospital_beds_per_thousand:{type:Schema.Types.Mixed},
    human_development_index:{type:Schema.Types.Mixed},
    icu_patients:{type:Schema.Types.Mixed},
    icu_patients_per_million:{type:Schema.Types.Mixed},
    iso_code:{type:String},
    life_expectancy:{type:Schema.Types.Mixed},
    location:{type:String},
    male_smokers:{type:Schema.Types.Mixed},
    median_age:{type:Schema.Types.Mixed},
    new_cases:{type:Schema.Types.Mixed},
    new_cases_per_million:{type:Schema.Types.Mixed},
    new_cases_smoothed:{type:Schema.Types.Mixed},
    new_cases_smoothed_per_million:{type:Schema.Types.Mixed},
    new_deaths:{type:Schema.Types.Mixed},
    new_deaths_per_million:{type:Schema.Types.Mixed},
    new_deaths_smoothed:{type:Schema.Types.Mixed},
    new_deaths_smoothed_per_million:{type:Schema.Types.Mixed},
    new_people_vaccinated_smoothed:{type:Schema.Types.Mixed},
    new_people_vaccinated_smoothed_per_hundred:{type:Schema.Types.Mixed},
    new_tests:{type:Schema.Types.Mixed},
    new_tests_per_thousand:{type:Schema.Types.Mixed},
    new_tests_smoothed:{type:Schema.Types.Mixed},
    new_tests_smoothed_per_thousand:{type:Schema.Types.Mixed},
    new_vaccinations:{type:Schema.Types.Mixed},
    new_vaccinations_smoothed:{type:Schema.Types.Mixed},
    new_vaccinations_smoothed_per_million:{type:Schema.Types.Mixed},
    people_fully_vaccinated:{type:Schema.Types.Mixed},
    people_fully_vaccinated_per_hundred:{type:Schema.Types.Mixed},
    people_vaccinated:{type:Schema.Types.Mixed},
    people_vaccinated_per_hundred:{type:Schema.Types.Mixed},
    population:{type:Schema.Types.Mixed},
    population_density:{type:Schema.Types.Mixed},
    positive_rate:{type:Schema.Types.Mixed},
    reproduction_rate:{type:Schema.Types.Mixed},
    stringency_index:{type:Schema.Types.Mixed},
    tests_per_case:{type:Schema.Types.Mixed},
    tests_units:{type:String},
    total_boosters:{type:Schema.Types.Mixed},
    total_boosters_per_hundred:{type:Schema.Types.Mixed},
    total_cases:{type:Schema.Types.Mixed},
    total_cases_per_million:{type:Schema.Types.Mixed},
    total_deaths:{type:Schema.Types.Mixed},
    total_deaths_per_million:{type:Schema.Types.Mixed},
    total_tests:{type:Schema.Types.Mixed},
    total_tests_per_thousand:{type:Schema.Types.Mixed},
    total_vaccinations:{type:Schema.Types.Mixed},
    total_vaccinations_per_hundred:{type:Schema.Types.Mixed},
    weekly_hosp_admissions:{type:Schema.Types.Mixed},
    weekly_hosp_admissions_per_million:{type:Schema.Types.Mixed},
    weekly_icu_admissions:{type:Schema.Types.Mixed},
    weekly_icu_admissions_per_million:{type:Schema.Types.Mixed}
});

// const dataSchema=new Schema({
//     iso_code:{type:String},
//     continent:{type:String},
//     location:{type:String},
//     date:{type:String},
//     total_cases:{type:String},
//     new_cases:{type:String},
//     new_cases_smoothed:{type:String},
//     total_deaths:{type:String},
//     new_deaths:{type:String},
//     new_deaths_smoothed:{type:String},
//     total_cases_per_million:{type:String},
//     new_cases_per_million:{type:String},
//     new_cases_smoothed_per_million:{type:String},
//     total_deaths_per_million:{type:String},
//     new_deaths_per_million:{type:String},
//     new_deaths_smoothed_per_million:{type:String},
//     reproduction_rate:{type:String},
//     icu_patients:{type:String},
//     icu_patients_per_million:{type:String},
//     hosp_patients:{type:String},
//     hosp_patients_per_million:{type:String},
//     weekly_icu_admissions:{type:String},
//     weekly_icu_admissions_per_million:{type:String},
//     weekly_hosp_admissions:{type:String},
//     weekly_hosp_admissions_per_million:{type:String},
//     total_tests:{type:String},
//     new_tests:{type:String},
//     total_tests_per_thousand:{type:String},
//     new_tests_per_thousand:{type:String},
//     new_tests_smoothed:{type:String},
//     new_tests_smoothed_per_thousand:{type:String},
//     positive_rate:{type:String},
//     tests_per_case:{type:String},
//     tests_units:{type:String},
//     total_vaccinations:{type:String},
//     people_vaccinated:{type:String},
//     people_fully_vaccinated:{type:String},
//     total_boosters:{type:String},
//     new_vaccinations:{type:String},
//     new_vaccinations_smoothed:{type:String},
//     total_vaccinations_per_hundred:{type:String},
//     people_vaccinated_per_hundred:{type:String},
//     people_fully_vaccinated_per_hundred:{type:String},
//     total_boosters_per_hundred:{type:String},
//     new_vaccinations_smoothed_per_million:{type:String},
//     new_people_vaccinated_smoothed:{type:String},
//     new_people_vaccinated_smoothed_per_hundred:{type:String},
//     stringency_index:{type:String},
//     population:{type:String},
//     population_density:{type:String},
//     median_age:{type:String},
//     aged_65_older:{type:String},
//     aged_70_older:{type:String},
//     gdp_per_capita:{type:String},
//     extreme_poverty:{type:String},
//     cardiovasc_death_rate:{type:String},
//     diabetes_prevalence:{type:String},
//     female_smokers:{type:String},
//     male_smokers:{type:String},
//     handwashing_facilities:{type:String},
//     hospital_beds_per_thousand:{type:String},
//     life_expectancy:{type:String},
//     human_development_index:{type:String},
//     excess_mortality_cumulative_absolute:{type:String},
//     excess_mortality_cumulative:{type:String},
//     excess_mortality:{type:String},
//     excess_mortality_cumulative_per_million:{type:String}

// });

// const dataSchema=new Schema({
//     titulo:{type:String}
// });

module.exports=model("data",dataSchema);